const plans=[{name:'DIY服务（纯DIY）',desc:'材料润色+流程指导，保持完全自主',price:'¥500起',link:'package.html',services:['简历润色500/篇','文书润色1000/篇','DIY答疑1888/年']},{name:'半DIY服务',desc:'材料专业支持+流程自主掌控',price:'¥3,999 套餐',link:'package.html',services:['简历1000/篇','文书2000/篇','全套材料3999']},{name:'全包服务',desc:'全流程代办+签证支持+进度跟踪',price:'¥10,000起',link:'package.html',services:['英港新8项目10000','15项目15000','超级混申20000']}];
const baseCases=Array.from({length:120},(_,i)=>{const countries=['英国','美国','加拿大','澳洲'];const degrees=['本科','硕士','博士'];const results=['Top50','Top100','奖学金'];const c=countries[i%4],d=degrees[i%3],r=results[i%3];return{id:i+1,title:`${c}${d}申请案例 #${i+1}`,background:`GPA ${(3+((i%10)/10)).toFixed(1)} / IELTS ${6+(i%3)*0.5}`,major:['商科','计算机','传媒','设计'][i%4],country:c,degree:d,result:r,school:['UCL','NYU','UBC','UNSW'][i%4],details:`${c}${d}方向，录取${['UCL','NYU','UBC','UNSW'][i%4]}，结果：${r}`};});
const faqs=[['我没有科研经历可以申请名校吗？','可以。我们会根据你的背景设计可执行的背景提升路径。'],['服务周期一般多久？','通常为3-10个月。'],['文书是模板化的吗？','不是，每份文书均一对一生成。']];
const testimonials=[['L同学','双非金融 → UCL MSc Management，拿到奖学金并成功转专业。'],['M同学','艺术设计作品集重构，3个月拿到SVA和RISD面试邀请。'],['Z家长','流程非常省心，签证和住宿环节全程有人跟进。']];
const timeline=['初步评估（1-2天）','定校策略（1周）','材料准备（2-8周）','网申递交（滚动）','面试/补件（按校）','签证行前（2-4周）'];

const planCards=document.getElementById('planCards');plans.forEach(p=>{const c=document.createElement('article');c.className='card';c.innerHTML=`<h3>${p.name}</h3><p>${p.desc}</p><div class="price">${p.price}</div><ul>${p.services.map(i=>`<li>${i}</li>`).join('')}</ul><a class="btn btn-primary" href="${p.link}" target="_blank" rel="noopener">了解更多</a>`;planCards.append(c)});

const searchInput=document.getElementById('searchInput'),countryFilter=document.getElementById('countryFilter'),degreeFilter=document.getElementById('degreeFilter'),resultFilter=document.getElementById('resultFilter');
const caseGrid=document.getElementById('caseGrid'),vizPanel=document.getElementById('vizPanel'),resultTip=document.getElementById('resultTip'),pager=document.getElementById('pager');
const pageSize=9;let currentPage=1;
const fillSelect=(el,label,vals)=>el.innerHTML=`<option value="">全部${label}</option>`+vals.map(v=>`<option>${v}</option>`).join('');
fillSelect(countryFilter,'国家',[...new Set(baseCases.map(c=>c.country))]);fillSelect(degreeFilter,'学历',[...new Set(baseCases.map(c=>c.degree))]);fillSelect(resultFilter,'结果',[...new Set(baseCases.map(c=>c.result))]);
const getFiltered=()=>{const kw=searchInput.value.trim();return baseCases.filter(c=>(!countryFilter.value||c.country===countryFilter.value)&&(!degreeFilter.value||c.degree===degreeFilter.value)&&(!resultFilter.value||c.result===resultFilter.value)&&(!kw||`${c.title}${c.background}${c.school}${c.major}`.includes(kw)))};
function renderViz(items){const byCountry=Object.entries(items.reduce((a,c)=>(a[c.country]=(a[c.country]||0)+1,a),{}));const max=Math.max(1,...byCountry.map(([,n])=>n));vizPanel.innerHTML=`<h3>数据可视化（按国家）</h3><div class="bars">${byCountry.map(([k,v])=>`<div class="bar-item"><small>${k} ${v}例</small><div class="bar-track"><div class="bar-fill" style="width:${(v/max)*100}%"></div></div></div>`).join('')}</div>`}
function render(){const items=getFiltered();const totalPage=Math.max(1,Math.ceil(items.length/pageSize));currentPage=Math.min(currentPage,totalPage);const pageItems=items.slice((currentPage-1)*pageSize,currentPage*pageSize);caseGrid.innerHTML=pageItems.map(i=>`<article class="case"><h3>${i.title}</h3><p>${i.background}</p><p><span class="pill">${i.country}</span><span class="pill">${i.degree}</span><span class="pill">${i.result}</span></p><p class="details">${i.major}｜${i.school}｜${i.details}</p></article>`).join('');renderViz(items);resultTip.textContent=`共 ${items.length} 条案例，当前第 ${currentPage}/${totalPage} 页`;pager.innerHTML=Array.from({length:totalPage},(_,i)=>`<button class="${i+1===currentPage?'active':''}" data-page="${i+1}">${i+1}</button>`).join('')}
[searchInput,countryFilter,degreeFilter,resultFilter].forEach(el=>el.addEventListener('input',()=>{currentPage=1;render()}));pager.addEventListener('click',e=>{if(e.target.dataset.page){currentPage=Number(e.target.dataset.page);render()}});render();

const faqList=document.getElementById('faqList');faqs.forEach(([q,a])=>{const i=document.createElement('div');i.className='accordion-item';i.innerHTML=`<button class="accordion-btn">${q}</button><div class="accordion-panel">${a}</div>`;i.querySelector('button').addEventListener('click',()=>i.classList.toggle('open'));faqList.append(i)});
const tBox=document.getElementById('testimonials');testimonials.forEach(([n,t])=>{const i=document.createElement('article');i.className='mini-card';i.innerHTML=`<h3>${n}</h3><p>${t}</p>`;tBox.append(i)});
const timelineBox=document.getElementById('timeline');timeline.forEach((t,idx)=>{const li=document.createElement('li');li.innerHTML=`<span>${idx+1}</span>${t}`;timelineBox.append(li)});

const header=document.getElementById('topHeader');window.addEventListener('scroll',()=>{header.classList.toggle('scrolled',window.scrollY>40);document.getElementById('hero').style.backgroundPositionY=`${window.scrollY*0.35}px`;document.getElementById('toTop').classList.toggle('show',window.scrollY>400)});
document.getElementById('toTop').addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}));
document.getElementById('themeToggle').addEventListener('click',()=>document.body.classList.toggle('dark'));
const observer=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.2});document.querySelectorAll('.fade-in').forEach(el=>observer.observe(el));
